FROM openjdk:17 as builder
WORKDIR /app

COPY pom.xml .
COPY mvnw .
COPY ./.mvn /app/.mvn

RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline
COPY ./src ./src
RUN ./mvnw clean install -DskipTests

FROM openjdk:17
WORKDIR /app
COPY --from=builder /app/target/*.jar /app/mrp.jar
ENTRYPOINT ["java", "-jar", "/mrp.jar"]